### PR TITLE
cleanup and rename

### PR DESCRIPTION
**Pull request by sertonix**
This pull request does the following:
- remove unused `.md`
- remove badges from `README.md`
- update repository url
- update `CONTRIBUTING.md`
- rename Atom to Pulsar
- remove `standard` linter

### CODE REVIEW

**Comment by sertonix** [comment]
@confused-Techie 
Since the standard linter was removed from the main repo I would also do that for other repos.
Should I do that in separate pull requests like #2 or include in my `cleanup and rename` pull requests?

Edit: same with `coffeelint`

**Comment by confused-Techie** [comment]
> @confused-Techie Since the standard linter was removed from the main repo I would also do that for other repos. Should I do that in separate pull requests like #2 or include in my `cleanup and rename` pull requests?
> 
> Edit: same with `coffeelint`

That one is totally up to your personnel preference.

Although in doing this I'd just make sure of a few things first.

1) The repo youre on is one of our core repos that can be bundled. As in does it appear in `packageDependencies`
2) That there is no GruntFile or scripts that rely on those dependencies

The reason I suggest this, is if it's not able to become a bundled dependency, it's a mute point mostly anyway, and also many of our repos do in fact use these scripts during install time, often through the GruntFile. And if removed could cause them to fail to install or build at all. The only reason we do it with core bundled packages, is because we know for a fact they aren't being used at all there, and are safe to remove

**Comment by sertonix** [comment]
Ok, I will check that they are really not used. But for example here they aren't so it should be safe to remove it.

**Review by confused-Techie — APPROVED** [review]
These changes look good to me!

Thanks a ton for the contribution!

Considering that this is a standalone package, I'll go ahead and tag the version here, and add a reminder to myself that we need to publish the new version to the store when possible. Otherwise I'll go ahead and merge

**Pull request merged**
